# server properties
server:
  port: 8081

# Secret Key To Generate Token
app:
  secretKey: '[@q2Xg7@T4mOplFu#Ae]'
  jwtValidityMinutes: 15
  
# spring properties
spring:
  application:
    name: AUTH-SERVICE  
    
# Configure Database here
  datasource:
    url: jdbc:mysql://localhost:3306/pension_management
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create 
    show-sql: false    
    
# Error Messages
jwtUtil:
  expiredMessage: Token has been expired
  malformedMessage: Token is in invalid format
  signatureMessage: Token signature is invalid
  nullOrEmptyMessage: Token is either null or empty
  unsupportedMessage: Claims for token is not supported
  
userDetails:
  errorMessage: User Does Not Exist!    