server:
  port: 8081
  
spring:
  application:
    name: AUTH-SERVICE  
    
# Configure Database here
  datasource:
    url: jdbc:mysql://localhost:3306/pension_management
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create 
    show-sql: false    