# server properties
server:
  port: 8082
  
# spring properties
spring:
  application:
    name: PROCESS-PENSION-SERVICE 
    
# Configure Database here
  datasource:
    url: jdbc:mysql://localhost:3306/process_pension
    username: student
    password: student
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create 
    show-sql: false

#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
logging:
  level:
    '[org.springframework.web]': ERROR
    '[com.cts.processPension]': DEBUG       