# server properties
server:
 port: 8083

# spring properties
spring:
 application:
  name: PENSIONER-DETAIL-SERVICE
  
#Eureka client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

# Error Messages
errorMessage: Aadhaar Number Not Found